version: "3.9"
services:
  cron:
    build: andrewjdawes/duckdns:latest
    secrets:
      - token
    volumes:
      - type: bind
        source: ./config.json
        target: /app/config.json
secrets:
  token:
    file: token.txt
